version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '06:00'
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
    groups:
      # The name of the group (identifier)
      npm-deps:
        update-types: [minor, patch]
    # Only allow minor and patch updates
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '06:05'
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
